In [29]:
import pandas as pd

In [30]:
jobs = pd.read_csv("../data/raw/postings.csv")

In [31]:
print(jobs.head())

     job_id            company_name  \
0    921716   Corcoran Sawyer Smith
1   1829192                     NaN
2  10998357  The National Exemplar
3  23221523  Abrams Fensterman, LLP
4  35982263                     NaN

                                               title  \
0                              Marketing Coordinator
1                  Mental Health Therapist/Counselor
2                        Assitant Restaurant Manager
3  Senior Elder Law / Trusts and Estates Associat...
4                                 Service Technician

                                         description  max_salary pay_period  \
0  Job descriptionA leading real estate firm in N...        20.0     HOURLY
1  At Aspen Therapy and Wellness , we are committ...        50.0     HOURLY
2  The National Exemplar is accepting application...     65000.0     YEARLY
3  Senior Associate Attorney - Elder Law / Trusts...    175000.0     YEARLY
4  Looking for HVAC service tech with experience ...     80000.0     YEARLY

            location  company_id  views  med_salary  ...  \
0      Princeton, NJ   2774458.0   20.0         NaN  ...
1   Fort Collins, CO         NaN    1.0         NaN  ...
2     Cincinnati, OH  64896719.0    8.0         NaN  ...
3  New Hyde Park, NY    766262.0   16.0         NaN  ...
4     Burlington, IA         NaN    3.0         NaN  ...

                                         skills_desc   listed_time  \
0  Requirements: \n\nWe are seeking a College or ...  1.713398e+12
1                                                NaN  1.712858e+12
2  We are currently accepting resumes for FOH - A...  1.713278e+12
3  This position requires a baseline understandin...  1.712896e+12
4                                                NaN  1.713452e+12

   posting_domain  sponsored  work_type currency compensation_type  \
0             NaN          0  FULL_TIME      USD       BASE_SALARY
1             NaN          0  FULL_TIME      USD       BASE_SALARY
2             NaN          0  FULL_TIME      USD       BASE_SALARY
3             NaN          0  FULL_TIME      USD       BASE_SALARY
4             NaN          0  FULL_TIME      USD       BASE_SALARY

  normalized_salary  zip_code     fips
0           38480.0    8540.0  34021.0
1           83200.0   80521.0   8069.0
2           55000.0   45202.0  39061.0
3          157500.0   11040.0  36059.0
4           70000.0   52601.0  19057.0

[5 rows x 31 columns]

In [32]:
print("Shape:", jobs.shape)

Shape: (123849, 31)

In [33]:
print(jobs.columns)

Index(['job_id', 'company_name', 'title', 'description', 'max_salary',
       'pay_period', 'location', 'company_id', 'views', 'med_salary',
       'min_salary', 'formatted_work_type', 'applies', 'original_listed_time',
       'remote_allowed', 'job_posting_url', 'application_url',
       'application_type', 'expiry', 'closed_time',
       'formatted_experience_level', 'skills_desc', 'listed_time',
       'posting_domain', 'sponsored', 'work_type', 'currency',
       'compensation_type', 'normalized_salary', 'zip_code', 'fips'],
      dtype='object')

In [34]:
print(jobs.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  object
 16  application_url             87184 non-null   object
 17  application_type            123849 non-null  object
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   object
 21  skills_desc                 2439 non-null    object
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   object
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  object
 26  currency                    36073 non-null   object
 27  compensation_type           36073 non-null   object
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), object(15)
memory usage: 29.3+ MB
None

In [35]:
print(jobs.isnull().sum())

job_id                             0
company_name                    1719
title                              0
description                        7
max_salary                     94056
pay_period                     87776
location                           0
company_id                      1717
views                           1689
med_salary                    117569
min_salary                     94056
formatted_work_type                0
applies                       100529
original_listed_time               0
remote_allowed                108603
job_posting_url                    0
application_url                36665
application_type                   0
expiry                             0
closed_time                   122776
formatted_experience_level     29409
skills_desc                   121410
listed_time                        0
posting_domain                 39968
sponsored                          0
work_type                          0
currency                       87776
compensation_type              87776
normalized_salary              87776
zip_code                       20872
fips                           27415
dtype: int64

In [36]:
print("Duplicates:", jobs.duplicated().sum())

Duplicates: 0

In [37]:
important_columns = [
    'job_id',
    'company_name',
    'title',
    'description',
    'formatted_work_type',
    'location',
    'formatted_experience_level',
    'skills_desc',
    'min_salary',
    'max_salary',
    'med_salary',
    'normalized_salary',
    'pay_period',
    'remote_allowed'
]

jobs = jobs[important_columns]

print(jobs.head())
print(jobs.shape)

     job_id            company_name  \
0    921716   Corcoran Sawyer Smith
1   1829192                     NaN
2  10998357  The National Exemplar
3  23221523  Abrams Fensterman, LLP
4  35982263                     NaN

                                               title  \
0                              Marketing Coordinator
1                  Mental Health Therapist/Counselor
2                        Assitant Restaurant Manager
3  Senior Elder Law / Trusts and Estates Associat...
4                                 Service Technician

                                         description formatted_work_type  \
0  Job descriptionA leading real estate firm in N...           Full-time
1  At Aspen Therapy and Wellness , we are committ...           Full-time
2  The National Exemplar is accepting application...           Full-time
3  Senior Associate Attorney - Elder Law / Trusts...           Full-time
4  Looking for HVAC service tech with experience ...           Full-time

            location formatted_experience_level  \
0      Princeton, NJ                        NaN
1   Fort Collins, CO                        NaN
2     Cincinnati, OH                        NaN
3  New Hyde Park, NY                        NaN
4     Burlington, IA                        NaN

                                         skills_desc  min_salary  max_salary  \
0  Requirements: \n\nWe are seeking a College or ...        17.0        20.0
1                                                NaN        30.0        50.0
2  We are currently accepting resumes for FOH - A...     45000.0     65000.0
3  This position requires a baseline understandin...    140000.0    175000.0
4                                                NaN     60000.0     80000.0

   med_salary  normalized_salary pay_period  remote_allowed
0         NaN            38480.0     HOURLY             NaN
1         NaN            83200.0     HOURLY             NaN
2         NaN            55000.0     YEARLY             NaN
3         NaN           157500.0     YEARLY             NaN
4         NaN            70000.0     YEARLY             NaN
(123849, 14)

In [38]:
null_percentages = (jobs.isnull().sum() / len(jobs)) * 100

null_df = pd.DataFrame({
    'Column': jobs.columns,
    'Null Percentage': null_percentages.values
})

null_df.sort_values(by='Null Percentage', ascending=False)

                        Column  Null Percentage
7                  skills_desc        98.030666
10                  med_salary        94.929309
13              remote_allowed        87.689848
8                   min_salary        75.944093
9                   max_salary        75.944093
11           normalized_salary        70.873402
12                  pay_period        70.873402
6   formatted_experience_level        23.745852
1                 company_name         1.387981
3                  description         0.005652
5                     location         0.000000
4          formatted_work_type         0.000000
2                        title         0.000000
0                       job_id         0.000000

In [39]:
jobs = jobs.drop(columns=['skills_desc'])

In [40]:
jobs = jobs.dropna(subset=[
    'title',
    'description',
    'location'
])

print(jobs.shape)

(123842, 13)

In [41]:
salary_data = jobs[
    jobs['normalized_salary'].notnull()
]

print("Jobs with salary data:", salary_data.shape)

Jobs with salary data: (36072, 13)

In [42]:
jobs['title'] = jobs['title'].str.lower()
jobs['description'] = jobs['description'].str.lower()

jobs['title'] = jobs['title'].str.strip()
jobs['description'] = jobs['description'].str.strip()

In [43]:
jobs = jobs.drop_duplicates(
    subset=['title', 'description']
)

print("Final Shape:", jobs.shape)

Final Shape: (110778, 13)

In [44]:
jobs.to_csv(
    "../data/processed/cleaned_jobs.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [45]:
print(jobs['description'].iloc[0])

job descriptiona leading real estate firm in new jersey is seeking an administrative marketing coordinator with some experience in graphic design. you will be working closely with our fun, kind, ambitious members of the sales team and our dynamic executive team on a daily basis. this is an opportunity to be part of a fast-growing, highly respected real estate brokerage with a reputation for exceptional marketing and extraordinary culture of cooperation and inclusion.who you are:you must be a well-organized, creative, proactive, positive, and most importantly, kind-hearted person. please, be responsible, respectful, and cool-under-pressure. please, be proficient in adobe creative cloud (indesign, illustrator, photoshop) and microsoft office suite. above all, have fantastic taste and be a good-hearted, fun-loving person who loves working with people and is eager to learn.role:our office is a fast-paced environment. you’ll work directly with a marketing team and communicate daily with other core staff and our large team of agents. this description is a brief overview, but your skills and interests will be considered in what you work on and as the role evolves over time.agent assistance- receive & organize marketing requests from agents- track tasks & communicate with marketing team & agents on status- prepare print materials and signs for open houses- submit orders to printers & communicate & track deadlinesgraphic design & branding- managing brand strategy and messaging through website, social media, videos, online advertising, print placement and events- receive, organize, and prioritize marketing requests from agents- fulfill agent design requests including postcards, signs, email marketing and property brochures using pre-existing templates and creating custom designs- maintain brand assets and generic filesevents & community- plan and execute events and promotions- manage contacts & vendors for event planning & sponsorshipsour company is committed to creating a diverse environment and is proud to be an equal opportunity employer. all qualified applicants will receive consideration for employment without regard to race, color, religion, gender, gender identity or expression, sexual orientation, national origin, genetics, disability, age, or veteran status.job type: full-time
pay: $18-20/hour
expected hours: 35 – 45 per week
benefits:paid time offschedule:8 hour shiftmonday to fridayexperience:marketing: 1 year (preferred)graphic design: 2 years (preferred)work location: in person

In [46]:
print(jobs['description'].iloc[10])

glastender inc. is a family-owned manufacturer of commercial bar and restaurant equipment, known for its high-quality products and innovative solutions. with a strong commitment to the customer experience, glastender has been serving the industry for over 50 years, providing establishments with state-of-the-art equipment and exceptional service.we are currently looking for an inside customer service associate who can communicate with outside customers by providing exceptional customer service by addressing their concerns and resolving issues promptly (inquiries, orders, and product information via phone and email). qualified candidates would be able to perform and possess the following skills:design bar equipment layouts using the best application of glastender products.compile and submit quotations, perform order verification, order entry, and complete detailed shop drawings for use in production.strong communication and organizational skills and demonstrated attention to detailstay updated on product knowledge and industry trends to effectively assist customers.maintain customer records and update the computer systems with relevant information.strong computer experience, with word processing and spreadsheet software (autocad software experience preferred). able to multi-task and navigate different software programs efficiently.experience in a business sales setting and/or college courses in business and marketing preferredprevious customer service experience requiredif you are excited about providing exceptional customer service and thrive in a collaborative team environment, we want to hear from you. you will play a pivotal role in supporting our sales team and ensuring a seamless experience for our customers. this position is perfect for individuals with a passion for customer service and a great approach to sales support.join glastender inc. and be a part of an industry leader committed to excellence in every aspect of our business.

In [47]:
print(jobs['description'].iloc[100])

primary duties include:

developing projects budgets

project estimating, bidding and writing detailed proposals

negotiating and preparing purchase orders, change orders, and subcontract agreements

scheduling (manpower and construction schedules)

maintaining project files and ensuring documents are complete and current

maintaining quality control and safety standards

coordinating daily task with superintendent and subcontractor

project closeout

send, receive, correct & modify project documents

coordinate and maintain vendor & supplier database records

reviewing submittals & specifications

communication with designer, owner, and subcontractors to foster strong relationships

ability to multi-task and establish priorities; strong management skills.

maintaining subcontractor relationships and performance

maintaining quality control and safety standards

material procurement and monitoring deliveries to jobsites

attend pre-bid/bid meetings

coordinate with upper level management

In [48]:
import re

In [49]:
def clean_text(text):

    # convert to string
    text = str(text)

    # lowercase
    text = text.lower()

    # replace contractions/apostrophes
    text = text.replace("’", "'")

    # remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)

    # remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # replace punctuation with spaces
    text = re.sub(r'[^\w\s]', ' ', text)

    # remove numbers
    text = re.sub(r'\d+', '', text)

    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [50]:
jobs['cleaned_description'] = jobs['description'].apply(clean_text)

In [51]:
print(jobs[['description', 'cleaned_description']].head(3))

                                         description  \
0  job descriptiona leading real estate firm in n...
1  at aspen therapy and wellness , we are committ...
2  the national exemplar is accepting application...

                                 cleaned_description
0  job descriptiona leading real estate firm in n...
1  at aspen therapy and wellness we are committed...
2  the national exemplar is accepting application...

In [52]:
sample_descriptions = jobs['description'].head()

In [53]:
for desc in sample_descriptions:
    print("BEFORE:\n")
    print(desc)

    print("\nAFTER:\n")
    print(clean_text(desc))

    print("\n" + "="*100 + "\n")

BEFORE:

job descriptiona leading real estate firm in new jersey is seeking an administrative marketing coordinator with some experience in graphic design. you will be working closely with our fun, kind, ambitious members of the sales team and our dynamic executive team on a daily basis. this is an opportunity to be part of a fast-growing, highly respected real estate brokerage with a reputation for exceptional marketing and extraordinary culture of cooperation and inclusion.who you are:you must be a well-organized, creative, proactive, positive, and most importantly, kind-hearted person. please, be responsible, respectful, and cool-under-pressure. please, be proficient in adobe creative cloud (indesign, illustrator, photoshop) and microsoft office suite. above all, have fantastic taste and be a good-hearted, fun-loving person who loves working with people and is eager to learn.role:our office is a fast-paced environment. you’ll work directly with a marketing team and communicate daily with other core staff and our large team of agents. this description is a brief overview, but your skills and interests will be considered in what you work on and as the role evolves over time.agent assistance- receive & organize marketing requests from agents- track tasks & communicate with marketing team & agents on status- prepare print materials and signs for open houses- submit orders to printers & communicate & track deadlinesgraphic design & branding- managing brand strategy and messaging through website, social media, videos, online advertising, print placement and events- receive, organize, and prioritize marketing requests from agents- fulfill agent design requests including postcards, signs, email marketing and property brochures using pre-existing templates and creating custom designs- maintain brand assets and generic filesevents & community- plan and execute events and promotions- manage contacts & vendors for event planning & sponsorshipsour company is committed to creating a diverse environment and is proud to be an equal opportunity employer. all qualified applicants will receive consideration for employment without regard to race, color, religion, gender, gender identity or expression, sexual orientation, national origin, genetics, disability, age, or veteran status.job type: full-time
pay: $18-20/hour
expected hours: 35 – 45 per week
benefits:paid time offschedule:8 hour shiftmonday to fridayexperience:marketing: 1 year (preferred)graphic design: 2 years (preferred)work location: in person

AFTER:

job descriptiona leading real estate firm in new jersey is seeking an administrative marketing coordinator with some experience in graphic design you will be working closely with our fun kind ambitious members of the sales team and our dynamic executive team on a daily basis this is an opportunity to be part of a fast growing highly respected real estate brokerage with a reputation for exceptional marketing and extraordinary culture of cooperation and inclusion who you are you must be a well organized creative proactive positive and most importantly kind hearted person please be responsible respectful and cool under pressure please be proficient in adobe creative cloud indesign illustrator photoshop and microsoft office suite above all have fantastic taste and be a good hearted fun loving person who loves working with people and is eager to learn role our office is a fast paced environment you ll work directly with a marketing team and communicate daily with other core staff and our large team of agents this description is a brief overview but your skills and interests will be considered in what you work on and as the role evolves over time agent assistance receive organize marketing requests from agents track tasks communicate with marketing team agents on status prepare print materials and signs for open houses submit orders to printers communicate track deadlinesgraphic design branding managing brand strategy and messaging through website social media videos online advertising print placement and events receive organize and prioritize marketing requests from agents fulfill agent design requests including postcards signs email marketing and property brochures using pre existing templates and creating custom designs maintain brand assets and generic filesevents community plan and execute events and promotions manage contacts vendors for event planning sponsorshipsour company is committed to creating a diverse environment and is proud to be an equal opportunity employer all qualified applicants will receive consideration for employment without regard to race color religion gender gender identity or expression sexual orientation national origin genetics disability age or veteran status job type full time pay hour expected hours per week benefits paid time offschedule hour shiftmonday to fridayexperience marketing year preferred graphic design years preferred work location in person

====================================================================================================

BEFORE:

at aspen therapy and wellness , we are committed to serving clients with best practices to help them with change, improvements and better quality of life. we believe in providing a secure, supportive environment to grow as a clinician and learn how to foster longevity in the career which is part of our mission statement.
thank you for taking the time to explore a career with us. we are excited to be a new group practice in the community. if you are looking for quality supervision as you work towards licensure and ability to serve populations while accepting a variety of insurance panels, we may be a good fit. our supervisors are trained in emdr and utilize a parts work perspective with a trauma lens.
we are actively looking to hire a therapist in the area who is passionate about working with adults and committed to growth and excellence in the field. we are located in old town square, fort collins.
we value and are strengthened by diversity and desire a warm and welcoming place for all people. we believe in racial and ethnic equality, gender equity and social inclusion.
position requirement possibilities:a graduate level psychological counseling-related degreemasters of social work (msw/lsw)licensed professional counselor candidate (lpcc)clinical social worker (lcsw)professional counselor (lpc)marriage/family therapist (lmft)relating to this?wanting to deliver high quality mental healthcareseeking quality supervision and growth in a healthy environmentwhat we offer:flexible work schedulew2 employment - commission basedbuilding to full time workjump of 5% in commission as well as monthly bonus/stipend once full timeweekly supervision providedpaid weekly team meetings $30/hrtwo paid wellness hours/month $30/hrtelemedicine and in-person flexibilitysupportive work environment with direct access to two supervisorsadministrative supportapproved professional development training providedfully automated ehr and technology supportstrong work/life balancejob duties:conducting intake assessmentsdeveloping and implementing treatment plans for clients based on assessment and coordinating any additional services needed, revising as necessaryconducting individual sessions as appropriate for the treatment plan of the patientapplying psychotherapeutic techniques and interventions in the delivery of services to individuals for the purpose of treating emotional and behavioral disorders that have been diagnosed in assessmentparticipating in team meetings in order to staff new cases. presenting appropriate patient information to the team. recommending effective treatment interventions.building and maintaining an active caseload with assigned clientscompleting timely progress notes and treatment updates in the ehr. maintaining all clinical documentation in accordance with regulatory and accrediting standardsproviding crisis intervention to patients in acute distress and referring as neededperforming case management and discharge planning as neededexcellent communication and interpersonal skillscompassionate and empathetic approach to patient careplease send resume and cover letter to info@aspentherapyandwellness.com
about aspen therapy and wellness llcaspen therapy and wellness is a mental health services provider focusing on work with adults in an outpatient setting, working with a variety of mental health issues both in-person in old town fort collins and throughout the state of colorado via telehealth services.
please note that this job description is not exhaustive and additional duties may be assigned as needed.

AFTER:

at aspen therapy and wellness we are committed to serving clients with best practices to help them with change improvements and better quality of life we believe in providing a secure supportive environment to grow as a clinician and learn how to foster longevity in the career which is part of our mission statement thank you for taking the time to explore a career with us we are excited to be a new group practice in the community if you are looking for quality supervision as you work towards licensure and ability to serve populations while accepting a variety of insurance panels we may be a good fit our supervisors are trained in emdr and utilize a parts work perspective with a trauma lens we are actively looking to hire a therapist in the area who is passionate about working with adults and committed to growth and excellence in the field we are located in old town square fort collins we value and are strengthened by diversity and desire a warm and welcoming place for all people we believe in racial and ethnic equality gender equity and social inclusion position requirement possibilities a graduate level psychological counseling related degreemasters of social work msw lsw licensed professional counselor candidate lpcc clinical social worker lcsw professional counselor lpc marriage family therapist lmft relating to this wanting to deliver high quality mental healthcareseeking quality supervision and growth in a healthy environmentwhat we offer flexible work schedulew employment commission basedbuilding to full time workjump of in commission as well as monthly bonus stipend once full timeweekly supervision providedpaid weekly team meetings hrtwo paid wellness hours month hrtelemedicine and in person flexibilitysupportive work environment with direct access to two supervisorsadministrative supportapproved professional development training providedfully automated ehr and technology supportstrong work life balancejob duties conducting intake assessmentsdeveloping and implementing treatment plans for clients based on assessment and coordinating any additional services needed revising as necessaryconducting individual sessions as appropriate for the treatment plan of the patientapplying psychotherapeutic techniques and interventions in the delivery of services to individuals for the purpose of treating emotional and behavioral disorders that have been diagnosed in assessmentparticipating in team meetings in order to staff new cases presenting appropriate patient information to the team recommending effective treatment interventions building and maintaining an active caseload with assigned clientscompleting timely progress notes and treatment updates in the ehr maintaining all clinical documentation in accordance with regulatory and accrediting standardsproviding crisis intervention to patients in acute distress and referring as neededperforming case management and discharge planning as neededexcellent communication and interpersonal skillscompassionate and empathetic approach to patient careplease send resume and cover letter to info aspentherapyandwellness com about aspen therapy and wellness llcaspen therapy and wellness is a mental health services provider focusing on work with adults in an outpatient setting working with a variety of mental health issues both in person in old town fort collins and throughout the state of colorado via telehealth services please note that this job description is not exhaustive and additional duties may be assigned as needed

====================================================================================================

BEFORE:

the national exemplar is accepting applications for an assistant restaurant manager.
we offer highly competitive wages, healthcare, paid time off, complimentary dining privileges and bonus opportunities.
we are a serious, professional, long-standing neighborhood restaurant with over 41 years of service. if you are looking for a long-term fit with a best in class organization then you should apply now.
please send a resumes to pardom@nationalexemplar.com. o

AFTER:

the national exemplar is accepting applications for an assistant restaurant manager we offer highly competitive wages healthcare paid time off complimentary dining privileges and bonus opportunities we are a serious professional long standing neighborhood restaurant with over years of service if you are looking for a long term fit with a best in class organization then you should apply now please send a resumes to pardom nationalexemplar com o

====================================================================================================

BEFORE:

senior associate attorney - elder law / trusts and estates  our legal team is committed to providing each client with quality counsel, innovative solutions, and personalized service. founded in 2000, the firm offers the legal expertise of its 115+ attorneys, who have accumulated experience and problem-solving skills over decades of practice.
we are a prominent lake success law firm seeking an associate attorney for its growing elder law and estate planning practice. the successful candidate will be a self-motivated, detail-oriented team member with strong communication skills and a desire to grow their practice. experience with estate planning, administration, and litigation and is preferred.
 responsibilities will include:
counseling clients with regard to estate planning and asset protection;formulating and overseeing execution of medicaid and estate plans;drafting wills, revocable and irrevocable trusts, powers of attorney, health care proxies, and living wills;estate administration;trust administration;court appearances for estate and proceedings;supervising paralegals
qualifications:juris doctor degree (j.d.) from an accredited law schoollicensed to practice law in new york10-15 years of experienceexperience with various advance directives, trusts, and willsstrong analytical and problem-solving skillsability to build rapport with clientsexcellent written and verbal communication skills
 competitive salary commensurate with experiencesalary: $140,000- $175,000benefits: 401k, medical, dental, life insurance, pto, and more
this position is based out of lake success, ny

AFTER:

senior associate attorney elder law trusts and estates our legal team is committed to providing each client with quality counsel innovative solutions and personalized service founded in the firm offers the legal expertise of its attorneys who have accumulated experience and problem solving skills over decades of practice we are a prominent lake success law firm seeking an associate attorney for its growing elder law and estate planning practice the successful candidate will be a self motivated detail oriented team member with strong communication skills and a desire to grow their practice experience with estate planning administration and litigation and is preferred responsibilities will include counseling clients with regard to estate planning and asset protection formulating and overseeing execution of medicaid and estate plans drafting wills revocable and irrevocable trusts powers of attorney health care proxies and living wills estate administration trust administration court appearances for estate and proceedings supervising paralegals qualifications juris doctor degree j d from an accredited law schoollicensed to practice law in new york years of experienceexperience with various advance directives trusts and willsstrong analytical and problem solving skillsability to build rapport with clientsexcellent written and verbal communication skills competitive salary commensurate with experiencesalary benefits k medical dental life insurance pto and more this position is based out of lake success ny

====================================================================================================

BEFORE:

looking for hvac service tech with experience in commerical and industrial equipment. minimum 5 yrs. on the job with mechanical license. winger is a full line union mechanical business with piping, plumbing, sheet metal and service.

AFTER:

looking for hvac service tech with experience in commerical and industrial equipment minimum yrs on the job with mechanical license winger is a full line union mechanical business with piping plumbing sheet metal and service

====================================================================================================

In [54]:
import sys
import os

sys.path.append(
    os.path.abspath("..")
)

from src.utils.skills import skills

In [55]:
print(skills[:10])

['python', 'java', 'javascript', 'c++', 'c#', 'sql', 'r', 'matlab', 'machine learning', 'deep learning']

In [56]:
import re

def extract_skills(text):

    found_skills = []

    for skill in skills:

        pattern = r'\b' + re.escape(skill) + r'\b'

        if re.search(pattern, text):
            found_skills.append(skill)

    return found_skills

In [57]:
jobs['extracted_skills'] = jobs[
    'cleaned_description'
].apply(extract_skills)

In [58]:
print(
    jobs[
        ['title', 'extracted_skills']
    ].head(15)
)

                                                title  \
0                               marketing coordinator
1                   mental health therapist/counselor
2                         assitant restaurant manager
3   senior elder law / trusts and estates associat...
4                                  service technician
5            economic development and planning intern
6                                            producer
7                                   building engineer
8                               respiratory therapist
9                                      worship leader
10                  inside customer service associate
11                                  project architect
12      appalachian highlands women's business center
13                                structural engineer
14                   senior product marketing manager

                                     extracted_skills
0                                                  []
1                                     [communication]
2                                                  []
3                    [communication, problem solving]
4                                                  []
5          [data analysis, communication, leadership]
6                                                  []
7     [communication, leadership, project management]
8                                                  []
9                                        [leadership]
10                                    [communication]
11                                       [leadership]
12  [excel, communication, leadership, project man...
13                                                 []
14                                    [communication]

In [59]:
tech_keywords = [
    'data',
    'software',
    'machine learning',
    'python',
    'developer',
    'engineer',
    'analyst',
    'ai',
    'cloud',
    'backend',
    'frontend',
    'full stack',
    'devops'
]

In [60]:
def is_tech_job(title):

    title = str(title).lower()

    for keyword in tech_keywords:
        if keyword in title:
            return True

    return False

In [61]:
tech_jobs = jobs[
    jobs['title'].apply(is_tech_job)
]

In [62]:
print("Original dataset shape:", jobs.shape)

print("Tech jobs dataset shape:", tech_jobs.shape)

Original dataset shape: (110778, 15)
Tech jobs dataset shape: (25627, 15)

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [64]:
vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

In [65]:
job_vectors = vectorizer.fit_transform(
    tech_jobs['cleaned_description']
)

In [66]:
print(job_vectors.shape)

(25627, 5000)

In [67]:
sample_resume = """
Aspiring Machine Learning Engineer with experience in Python,
SQL, TensorFlow, Scikit-learn, data analysis, deep learning,
and NLP projects.

Built machine learning models for prediction and recommendation systems.
Worked with Power BI, Tableau, Git, AWS, and data visualization tools.

Strong communication, leadership, and problem-solving skills.
"""

In [68]:
resume_vector = vectorizer.transform(
    [sample_resume]
)

In [69]:
similarity_scores = cosine_similarity(
    resume_vector,
    job_vectors
)

In [70]:
print(similarity_scores.shape)

(1, 25627)

In [71]:
top_indices = similarity_scores.argsort()[0][-5:][::-1]

In [72]:
print(top_indices)

[24078 10635 21279 12275  2602]

In [73]:
recommended_jobs = tech_jobs.iloc[top_indices][
    [
        'title',
        'company_name',
        'location',
        'extracted_skills'
    ]
]

In [74]:
print(recommended_jobs)

                                           title                company_name  \
116439            lead machine learning engineer           Confidential Jobs
51764       sr genai / machine learning engineer                      Deltek
100458        machine learning engineer - remote    Orbit Recruitment Group
59274                  machine learning engineer                eduPhoria.ai
13074   junior data scientist - python /modeling  Expert Technical Solutions

                         location  \
116439              United States
51764               United States
100458     Los Angeles County, CA
59274   California, United States
13074                 Atlanta, GA

                                         extracted_skills
116439  [python, java, machine learning, deep learning...
51764   [python, machine learning, deep learning, tens...
100458  [python, machine learning, tensorflow, pytorch...
59274   [python, r, machine learning, data analysis, d...
13074   [python, r, machine learning, deep learning, d...

In [75]:
top_scores = similarity_scores[0][top_indices]

In [76]:
recommended_jobs = recommended_jobs.copy()

recommended_jobs['match_score'] = (
    top_scores * 100
).round(2)

In [77]:
recommended_jobs = recommended_jobs.sort_values(
    by='match_score',
    ascending=False
)

In [78]:
print(recommended_jobs)

                                           title                company_name  \
116439            lead machine learning engineer           Confidential Jobs
51764       sr genai / machine learning engineer                      Deltek
100458        machine learning engineer - remote    Orbit Recruitment Group
59274                  machine learning engineer                eduPhoria.ai
13074   junior data scientist - python /modeling  Expert Technical Solutions

                         location  \
116439              United States
51764               United States
100458     Los Angeles County, CA
59274   California, United States
13074                 Atlanta, GA

                                         extracted_skills  match_score
116439  [python, java, machine learning, deep learning...        50.57
51764   [python, machine learning, deep learning, tens...        46.43
100458  [python, machine learning, tensorflow, pytorch...        46.07
59274   [python, r, machine learning, data analysis, d...        44.38
13074   [python, r, machine learning, deep learning, d...        44.11

In [79]:
def recommend_jobs(resume_text, top_n=5):

    # Clean resume
    cleaned_resume = clean_text(resume_text)

    # Convert resume to vector
    resume_vector = vectorizer.transform(
        [cleaned_resume]
    )

    # Calculate similarity
    similarity_scores = cosine_similarity(
        resume_vector,
        job_vectors
    )

    # Get top matches
    top_indices = similarity_scores.argsort()[0][-top_n:][::-1]

    # Get scores
    top_scores = similarity_scores[0][top_indices]

    # Fetch jobs
    recommendations = tech_jobs.iloc[top_indices][
        [
            'title',
            'company_name',
            'location',
            'extracted_skills'
        ]
    ].copy()

    # Add scores
    recommendations['match_score'] = (
        top_scores * 100
    ).round(2)

    return recommendations

In [80]:
recommend_jobs(sample_resume)

,title,company_name,location,extracted_skills,match_score
116439,lead machine learning engineer,Confidential Jobs,United States,"[python, java, machine learning, deep learning...",50.57
51764,sr genai / machine learning engineer,Deltek,United States,"[python, machine learning, deep learning, tens...",46.43
100458,machine learning engineer - remote,Orbit Recruitment Group,"Los Angeles County, CA","[python, machine learning, tensorflow, pytorch...",46.07
59274,machine learning engineer,eduPhoria.ai,"California, United States","[python, r, machine learning, data analysis, d...",44.38
13074,junior data scientist - python /modeling,Expert Technical Solutions,"Atlanta, GA","[python, r, machine learning, deep learning, d...",44.11

# Resume Parsing

In [81]:
import fitz

In [82]:
def extract_resume_text(pdf_path):

    text = ""

    pdf = fitz.open(pdf_path)

    for page in pdf:

        text += page.get_text()

    return text

In [83]:
resume_text = extract_resume_text(
    "../data/resumes/sample_resume.pdf"
)

In [84]:
print(resume_text[:2000])

OM MISHRA
+91-8805716087 ⋄ Pune, India
om.mishra.2410@gmail.com ⋄ LinkedIn ⋄ Github
OBJECTIVE
I’m an aspiring Machine Learning Developer with hands-on experience working on data-driven projects and building
predictive models. I specialize in Python, data analysis, and core machine learning techniques, and I focus on solving real-
world problems by turning data into meaningful insights and practical solutions. Currently working on machine learning
projects and continuously improving my skills.
EDUCATION
Bachelors Of Engineering, AISSMS COE
August 2023- July 2027
Relevant Coursework: Computer Science CGPA-8.20
SKILLS
Data & Machine Learning   Data Analysis, Machine Learning, Data Preprocessing, Feature Engineering, Model Evaluation
Programming Languages     Python, C++, SQL
Libraries & Tools                   Pandas, NumPy, Scikit-learn, Matplotlib
Visualization Tools               Power BI, Tableau
Core Concepts                       Data Structures & Algorithms ,Object-Oriented Programming (OOP)
Tools                                       Git, GitHub, Jupyter Notebook, VS Code

EXPERIENCE
Data Science & AI Consultant — Rubixe AI                                                                                          [Jan 2026 – Present]

 Analyze structured datasets using Python (Pandas, NumPy)
 Perform data cleaning, preprocessing, and EDA
 Build basic ML models using Scikit-learn
 Apply feature engineering to improve model performance
PROJECTS

Portuguese Bank Marketing Prediction      |  Github
- Trained classification model to predict term deposit subscription
- Handled categorical encoding and missing values during preprocessing
- Evaluated performance using accuracy and confusion matrix

Liver Patient Prediction                                  |  Github
- Built classification model to detect liver disease from medical data
- Performed data cleaning and feature selection
- Evaluated model using standard classification

In [85]:
recommendations = recommend_jobs(
    resume_text,
    top_n=5
)

In [86]:
print(recommendations)

                                     title  \
116439      lead machine learning engineer
100458  machine learning engineer - remote
42695             principal data scientist
59274            machine learning engineer
55205                senior data scientist

                                   company_name                   location  \
116439                        Confidential Jobs              United States
100458                 Orbit Recruitment Group      Los Angeles County, CA
42695                    Denken Solutions, Inc.             Round Rock, TX
59274                              eduPhoria.ai  California, United States
55205   Optimus - People. Solutions. Delivered.            Greater Houston

                                         extracted_skills  match_score
116439  [python, java, machine learning, deep learning...        48.59
100458  [python, machine learning, tensorflow, pytorch...        39.38
42695   [python, r, machine learning, data science, py...        39.36
59274   [python, r, machine learning, data analysis, d...        39.11
55205   [python, sql, r, machine learning, data analys...        37.91

In [87]:
resume_skills = extract_skills(
    clean_text(resume_text)
)

print(resume_skills)

['python', 'sql', 'machine learning', 'data analysis', 'data science', 'git', 'power bi', 'tableau']

In [88]:
def calculate_skill_overlap(
    resume_skills,
    job_skills
):

    resume_set = set(resume_skills)

    job_set = set(job_skills)

    overlap = resume_set.intersection(job_set)

    return len(overlap)

In [89]:
print(
    calculate_skill_overlap(
        ['python', 'sql', 'aws'],
        ['python', 'tensorflow', 'aws']
    )
)

2

In [90]:
def get_matched_skills(
    resume_skills,
    job_skills
):

    return list(
        set(resume_skills).intersection(
            set(job_skills)
        )
    )

In [91]:
def hybrid_recommend_jobs(
    resume_text,
    top_n=5
):

    # Clean resume
    cleaned_resume = clean_text(resume_text)

    # Extract resume skills
    resume_skills = extract_skills(
        cleaned_resume
    )

    # Vectorize resume
    resume_vector = vectorizer.transform(
        [cleaned_resume]
    )

    # Semantic similarity
    similarity_scores = cosine_similarity(
        resume_vector,
        job_vectors
    )[0]

    # Copy tech jobs
    recommendations = tech_jobs.copy()

    # Add similarity score
    recommendations['similarity_score'] = (
        similarity_scores * 100
    )

    # Skill overlap score
    recommendations['skill_overlap'] = (
        recommendations['extracted_skills']
        .apply(
            lambda job_skills:
            calculate_skill_overlap(
                resume_skills,
                job_skills
            )
        )
    )

    # Matched skills
    recommendations['matched_skills'] = (
        recommendations['extracted_skills']
        .apply(
            lambda job_skills:
            get_matched_skills(
                resume_skills,
                job_skills
            )
        )
    )

    # Final hybrid score
    recommendations['final_score'] = (
        recommendations['similarity_score']
        +
        recommendations['skill_overlap'] * 5
    )

    # Sort by final score
    recommendations = recommendations.sort_values(
        by='final_score',
        ascending=False
    )

    return recommendations[
        [
            'title',
            'company_name',
            'location',
            'extracted_skills',
            'similarity_score',
            'skill_overlap',
            'matched_skills',
            'final_score'
        ]
    ].head(top_n)

In [92]:
hybrid_recommend_jobs(
    resume_text
)

,title,company_name,location,extracted_skills,similarity_score,skill_overlap,matched_skills,final_score
116439,lead machine learning engineer,Confidential Jobs,United States,"[python, java, machine learning, deep learning...",48.592588,5,"[python, power bi, tableau, machine learning, ...",73.592588
55205,senior data scientist,Optimus - People. Solutions. Delivered.,Greater Houston,"[python, sql, r, machine learning, data analys...",37.906413,7,"[sql, python, power bi, tableau, data analysis...",72.906413
94504,data scientist,RTeams,United States,"[python, sql, r, machine learning, data analys...",34.266525,7,"[sql, python, tableau, data analysis, machine ...",69.266525
24895,data scientist (human services experience),FUSTIS LLC,Washington DC-Baltimore Area,"[python, sql, r, machine learning, data analys...",33.470190,7,"[sql, python, power bi, tableau, data analysis...",68.470190
87454,data scientist,Unified Women's Healthcare,"Florida, United States","[python, sql, machine learning, data science, ...",31.485394,7,"[sql, python, power bi, tableau, machine learn...",66.485394